# Identificadores del proyecto
sonar.projectKey=Centro-Medico-Pichardo
sonar.projectName=Centro Medico Pichardo

# Ubicación del código y exclusiones
sonar.sources=.
sonar.exclusions=node_modules/**, .next/**, out/**, public/**

# Configuración de lenguaje
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8

# NOTA: No pongas el token ni la URL aquí para evitar vulnerabilidades críticas